services:
  # executor:
  #   build:
  #     context: ./executor
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - agent-network
  #   mem_limit: 512m
  #   cpus: 1.0

  # orchestrator:
  #   build:
  #     context: ./orchestrator
  #   environment:
  #     # Windowsホスト側で動くOllama等のAPIアドレスを指定
  #     - LLM_API_BASE=http://host.docker.internal:11434
  #   depends_on:
  #     - executor
  #   networks:
  #     - agent-network
  tester:
    build:
      context: ./tester
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_KNOWLEDGE_BASE_ID
      - LLM_API_BASE
      - OLLAMA_MODEL
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python", "app.py"]

# networks:
#   agent-network:
#     driver: bridge